export const charactersList = [
  {
    id: 1,
    name: "Robbie",
    race: "Human",
    alignment: 'foiasdjf',
    xp: 10,
    class: "warrior",
    level: 5,
    proeficiencyBonus: 10,
    strenght: {field1: 1, field2: 2, savingThrows: {field1: 1, field2: 1}, athletics: {field1: 1, field2: 1}},
    dexterity: {field1: 1, field2: 1, savingThrows:{field1: 1, field2: 1}, acrobatics:{field1: 1, field2: 1}, sleightOfHand: {field1: 1, field2: 1}, stealth: {field1: 1, field2: 1}},
    constitution: {field1: 1, field2: 1, savingThrows:{field1: 1, field2: 1}},
    inteligence: {field1: 1, field2: 1, savingThrows:{field1: 1, field2: 1}, arcana:{field1: 1, field2: 1}, history:{field1: 1, field2: 1}, investigation:{field1: 1, field2: 1},nature:{field1: 1, field2: 1},religion:{field1: 1, field2: 1}},
    wisdom:{field1: 1, field2: 1, savingThrows:{field1: 1, field2: 1}, deception:{field1: 1, field2: 1}, indimidation:{field1: 1, field2: 1}, performance:{field1: 1, field2: 1}, persuasion:{field1: 1, field2: 1}},
    passiveWisdom: 10,
    otherProeficiencyAndLanguages: ['Elf language'],
    features: ['six fingers on the left hand', 'only one eyebrow'],
    dexMod: 5,
    naturalArmor: 10,
    armor: 6,
    shield: 7,
    misc: 0,
    deathSaves: {successes: [1,3,6], failures:[2,4,5]},
    speelCastingAbility: 1,
    spellSaveDC: 3,
    spellAttackBonus: 4,
    sorcererPSIKIpoints: 10,
    attacks: [{weapon: 'sword', type: 'blade', range: 'close', atkBonus: 4, damage: 7}],
    maxHP: 100,
    currentHitPoints: 20,
    tempHP: 9,
    initiative: 10,
    speed: 8,
    inspiration: 10,
    spells: [{field1: 1, spell: 'confusion spell', level: 7}],
    equipmentAndTreasure: {cp: 1, sp: 6, gp: 6, pp: 3, bag: ['health potion', 'potato']}
  },
];
